#!/usr/bin/env python3
"""Convert the QMK doio/kb16 Bongo Cat animation frames to a ZMK LVGL images file.

Reads the 8 (128x32) frames from the QMK keymap source
`keyboards/doio/kb16/lib/bongocat/bongocat.c`, which stores each frame in
SSD1306 page-major byte order (byte = 8 vertical pixels, LSB = top row -
QMK's oled driver sets pixels with `1 << (y % 8)` - pages top-to-bottom,
columns left-to-right). Emits a `bongo_cat_images.c` with each frame as an
LVGL `LV_IMG_CF_INDEXED_1BIT` image descriptor in row-major 1bpp order
(MSB = leftmost pixel), palette [white, black].

The Keyball44 OLED is configured `inversion-on` (keyball44.dtsi), so a lit
pixel corresponds to a GDDRAM bit of 0. Index 1 (the cat, bit=1 in the QMK
frames) maps to black in LVGL, which the inverted display renders lit;
index 0 (background) maps to white, rendered dark. This matches the palette
order used by ZMK's own status-screen icons.

Usage:
    python3 convert_bongo_frames.py <bongocat.c> <bongo_cat_images.c>
"""

import re
import sys

WIDTH = 128
HEIGHT = 32
BYTES_PER_FRAME = WIDTH * HEIGHT // 8  # 512
# The QMK source declares each frame as [ANIM_SIZE] but writes exactly
# BYTES_PER_FRAME explicit bytes; the 13 remaining bytes are zero-filled.
ANIM_SIZE = 525
ROWS = (WIDTH + 7) // 8  # 16 bytes per row

NAMES = [
    "bongo_idle1",
    "bongo_idle2",
    "bongo_idle3",
    "bongo_idle4",
    "bongo_idle5",
    "bongo_prep",
    "bongo_tap1",
    "bongo_tap2",
]


def parse_frames(path):
    with open(path, "r") as f:
        data = f.read()
    tokens = re.findall(r"0x[0-9a-fA-F]{2}", data)
    expected = 8 * BYTES_PER_FRAME
    if len(tokens) < expected:
        raise SystemExit(
            f"expected at least {expected} byte literals in {path}, found {len(tokens)}"
        )
    frames = []
    for i in range(8):
        frame = [int(t, 16) for t in tokens[i * BYTES_PER_FRAME : (i + 1) * BYTES_PER_FRAME]]
        frames.append(frame)
    return frames


def to_row_major(frame):
    """Transpose SSD1306 page-major bytes to LVGL row-major 1bpp."""
    out = bytearray(HEIGHT * ROWS)
    for y in range(HEIGHT):
        page = y >> 3
        bit = y & 7  # LSB = topmost row of the page (QMK oled_write_pixel)
        for x in range(WIDTH):
            if (frame[page * WIDTH + x] >> bit) & 1:
                idx = y * ROWS + (x >> 3)
                out[idx] |= 0x80 >> (x & 7)
    return bytes(out)


def c_hex_bytes(data, per_line=16):
    lines = []
    for i in range(0, len(data), per_line):
        chunk = data[i : i + per_line]
        lines.append(
            "  " + ", ".join(f"0x{b:02x}" for b in chunk) + ("," if i + per_line < len(data) else "")
        )
    return "\n".join(lines)


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    src, dst = sys.argv[1], sys.argv[2]
    frames = [to_row_major(f) for f in parse_frames(src)]

    out = []
    out.append("/*")
    out.append(" * Copyright (c) 2026 The Bongocat ZMK Contributors")
    out.append(" * SPDX-License-Identifier: MIT")
    out.append(" *")
    out.append(" * Generated by tools/convert_bongo_frames.py from")
    out.append(" * keyboards/doio/kb16/lib/bongocat/bongocat.c (QMK).")
    out.append(" * Each image: LV_IMG_CF_INDEXED_1BIT, 128x32, row-major 1bpp,")
    out.append(" * 8-byte palette [white, black], data_size = 520.")
    out.append(" */")
    out.append("")
    out.append("#include <lvgl.h>")
    out.append("")
    out.append("#ifndef LV_ATTRIBUTE_MEM_ALIGN")
    out.append("#define LV_ATTRIBUTE_MEM_ALIGN")
    out.append("#endif")
    out.append("")

    for name, frame in zip(NAMES, frames):
        up = name.upper()
        out.append(f"#ifndef LV_ATTRIBUTE_IMG_{up}")
        out.append(f"#define LV_ATTRIBUTE_IMG_{up}")
        out.append("#endif")
        out.append("")
        out.append(
            f"const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_IMG_{up} "
            f"uint8_t {name}_map[] = {{"
        )
        out.append("  0xff, 0xff, 0xff, 0xff, /*Color of index 0*/")
        out.append("  0x00, 0x00, 0x00, 0xff, /*Color of index 1*/")
        out.append("")
        out.append(c_hex_bytes(frame))
        out.append("};")
        out.append("")
        out.append(f"const lv_img_dsc_t {name} = {{")
        out.append("  .header.cf = LV_IMG_CF_INDEXED_1BIT,")
        out.append("  .header.always_zero = 0,")
        out.append("  .header.reserved = 0,")
        out.append("  .header.w = 128,")
        out.append("  .header.h = 32,")
        out.append("  .data_size = 520,")
        out.append(f"  .data = {name}_map,")
        out.append("};")
        out.append("")

    with open(dst, "w") as f:
        f.write("\n".join(out))

    print(f"wrote {dst} ({len(frames)} frames, "
          f"{len(frames) * (8 + BYTES_PER_FRAME)} bytes of image data)")


if __name__ == "__main__":
    main()
